### ISSUE TITLE
Replicating Sign Text with sgnw-components

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/sgnw-components#2]
Hi,
I have a few signs written in sign writing, and I would like to show them in a nice column like in https://slevinski.github.io/SuttonSignWriting/characters/index.html

![image](https://user-images.githubusercontent.com/5757359/122436997-9283f700-cf99-11eb-9d4f-d7ed9089c815.png)

For this example, my signs are:
> M507x523S15a28494x496S26500493x477
M522x525S11541498x491S11549479x498S20600489x476
AS14c31S14c39S27102S27116S30300S30a00S36e00M554x585S30a00481x488S30300481x477S14c31508x546S14c39465x545S36e00477x523S27102539x545S27116445x545

I tried using the `sgnw-sign` component:
```html
    <sgnw-sign fsw="M507x523S15a28494x496S26500493x477"></sgnw-sign>
    <sgnw-sign fsw="M522x525S11541498x491S11549479x498S20600489x476"></sgnw-sign>
    <sgnw-sign fsw="AS14c31S14c39S27102S27116S30300S30a00S36e00M554x585S30a00481x488S30300481x477S14c31508x546S14c39465x545S36e00477x523S27102539x545S27116445x545"></sgnw-sign>
```

Which resulted in:
![image](https://user-images.githubusercontent.com/5757359/122437364-ef7fad00-cf99-11eb-86da-371c945c909f.png)

This is
1. quite small
2. not nicely aligned

Is there a way using the components to display a nice orderly sequence of signs?

**Comment by Slevinski** [comment]
This component isn't available yet.  I have two components planned, <sgnw-p> for horizontal paragraph and <sgnw-vp> for vertical paragraph.  I've been sidetracked by other concerns and haven't made these yet.  I will bump this issue towards the top of the list.

**Comment by Slevinski** [comment]
A new version of the sgnw-components has been released that updates the dependencies and reduces the complexity.  I'm excited to start work on the <sgnw-vp> component.  It should be ready in a few weeks.

**Comment by Slevinski** [comment]
Version 1.0 has been released with vertical paragraphs.
