### ISSUE TITLE
Performance - Load the SignWriting font locally

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/sgnw-components#3]
I'm building an app that uses `sgnw-components`.
It seems like that when registering the custom elements here, two requests go out to load the fonts from a third party domain:
- https://cdn.jsdelivr.net/npm/@sutton-signwriting/font-ttf@1.0.0/font/SuttonSignWritingLine.ttf
- https://cdn.jsdelivr.net/npm/@sutton-signwriting/font-ttf@1.0.0/font/SuttonSignWritingFill.ttf

This is a bit problematic, as requests to an external domain create a new SSL handshake (as indicated by the purple), and are more difficult to set a service-worker cache policy for. 
Additionally, loading these fonts from a third party might make the app unusable in offline mode.

See waterfall chart of the app loading time: (these fonts take the majority of the time)

![image](https://user-images.githubusercontent.com/5757359/126027672-1b2e7803-bfeb-479c-a808-fbce59c46560.png)

## One possible solution:

For apps using a build process (angular apps, stencil apps, etc), they install the library using:
`npm install @sutton-signwriting/sgnw-components --save`

This also installs the `@sutton-signwriting/font-ttf` as a dependency.

In the `font-ttf` library, add to the `font` directory a `font.css` file:
```
@font-face {
    font-family: SuttonSignWritingLine;
    src: url("SuttonSignWritingLine.ttf") format("truetype");
}
@font-face {
    font-family: SuttonSignWritingFill;
    src: url("SuttonSignWritingFill.ttf") format("truetype");
}
```

For everyone using the library with a script tag, they would need to do:
```html
<script src="node_modules/@sutton-signwriting/sgnw-components/dist/sgnw-components.js"></script>
<link rel="stylesheet" href="node_modules/@sutton-signwriting/font-ttf/font/font.css">
```

But in Angular, for example, I would add something like this to the config, and angular should correctly resolve the paths:
```json
"assets": [
  "src/assets",
  {
    "glob": "**/*",
    "input": "./node_modules/@sutton-signwriting/font-ttf/font",
    "output": "./assets/fonts/signwriting/"
  }
],
"styles": [
  "src/theme/styles.scss",
  "assets/fonts/signwriting/font.css"
],
```

---

Thanks for all of your hard work on this Steve!

**Comment by Slevinski** [comment]
There are three scenarios here.  They can all be handled by the SignWriting fonts.  Some assembly required.

1) Fonts installed on local computer already  (Windows, Mac, Linux, iOS)
2) Fonts packaged with the website/application
3) Fonts available on the internet.

For the @sutton-signwriting/font-ttf package function font.cssAppend, it will always handle scenarios 1 and 3.  For scenario 2, you will need to pass the font.cssAppend function the location of the locally available font files, or you will need to create the CSS font-face yourself.

See: https://sutton-signwriting.github.io/font-ttf/#fontcssappend

**Comment by AmitMY** [comment]
Thanks Steve!

### Final code:

Copy ttf files:
```json
{
  "glob": "*.ttf",
  "input": "./node_modules/@sutton-signwriting/font-ttf/font",
  "output": "./assets/fonts/signwriting/"
}
```

Set directory:
```ts
import {font} from '@sutton-signwriting/font-ttf/index.js';

font.cssAppend('assets/fonts/signwriting/');
```

## Waterfall
![image](https://user-images.githubusercontent.com/5757359/126442032-1b548720-cc36-49a8-ab89-a1f622b0741f.png)
