### ISSUE TITLE
Distribution without including other packages

### ISSUE THREAD

**Issue by AmitMY** [sutton-signwriting/sgnw-components#9]
Currently, the `dist` directory, file `custom-elements/index.js` for example, includes 
![image](https://user-images.githubusercontent.com/5757359/162987321-88be655d-6742-42f1-93e9-ee0b740dae1c.png)

I believe that might come from importing the `js` files directly, and not importing a `package target`
![image](https://user-images.githubusercontent.com/5757359/162987632-91da8c74-ae23-4e12-bfcc-e5c4351eded2.png)

This creates code duplication, and hard setting of dependencies.

**Comment by Slevinski** [comment]
I will take a look at this later this month.  I am planning a new version of the sgnw-components after I finish the update for the @sutton-signwriting/font-db project

**Comment by Slevinski** [comment]
Looks like a good change to remove the filename at the end for all of the imports.  The custom-elements/index.js went from 38 K to 22 K.  This change will be available in the next release.

**Comment by AmitMY** [comment]
Thanks @Slevinski 
any eta on that release?

**Comment by Slevinski** [comment]
I am planning to have a v1.0 release by the end of this month.

**Comment by AmitMY** [comment]
Hi @Slevinski 
Just to give more perspective, besides the very nice decrease in bundle size, this is actually blocking https://github.com/sign/translate/pull/27 because the fix - https://github.com/sutton-signwriting/font-ttf/issues/2 - is not included in the release, and instead it uses the old version

**Comment by Slevinski** [comment]
Hi @AmitMY
Thanks for the related information.  I will get a release this weekend for sure. I'm currently cleaning up a mess from trying to integrate Storybook.  It almost worked, but had too many issues.  I'll straighten out the documentation and publish.

**Comment by Slevinski** [comment]
Hi @AmitMY 

A new version has been published.  Please git it a try

**Comment by AmitMY** [comment]
Thanks! Can confirm, the latest release makes server side rendering possible :)
